### ISSUE TITLE
simplify branching strategy

### ISSUE THREAD

**Issue by davidchambers** [huafu/hubot-gitter2#31]
@huafu, currently we have `develop` and `master` branches. I do not think this is necessary. I suggest merging the branches, deleting `develop`, and merging all future pull requests into `master` directly. Do you support this? Say the word and I will take care of it. :)

**Comment by huafu** [comment]
I was just following git flow, where `develop` is the current development branch where everything get merged, and then when we are ready for a release, we merge `develop` into `master`, create a tag out of it, and merge back `master` into `develop`. This to ensure that master is nothing else but the last release.

Tho if you think it's simpler having only master it's up to you since for now you'll be the one dealing with it. I guess we can always come back to git flow later if needed anyway. In that case don't forget to put `master` as the default branch in repo settings ;-)

Thanks again for your work on this!

**Comment by davidchambers** [comment]
Thanks for responding so quickly, Huafu.

Tasks:

1.  [x] Merge `develop` into `master`, locally
2.  [x] Push local `master` to remote
3.  [x] Change base branch of #27 from `develop` to `master`
4.  [x] Rebase #27 atop `master`
5.  [x] Change base branch of #22 from `develop` to `master`
6.  [x] Change default branch to `master` in repository settings
7.  [x] Delete `develop`

I don't have access to the repository settings. Please either grant me access or change the default branch yourself. :)

**Comment by huafu** [comment]
I try to look at GitHub notifications every day since I gave you access, for the help you're giving I must at least respond quickly to any of your questions or requests ;-)

I changed the default branch to `master` now, I don't think I can give you access to the repo settings anyway.

**Comment by davidchambers** [comment]
Thanks. I just deleted `develop`, resolving this issue.
